### ISSUE TITLE
(2019-9月)今天学了什么?

### ISSUE THREAD

**Issue by xixigiggling** [xixigiggling/my-ice-cream#33]
#### 2019-09-03

1. css画三角形

```css
#triangle-up {
    width: 0;
    height: 0;
    border-left: 50px solid transparent;
    border-right: 50px solid transparent;
    border-bottom: 100px solid red;
}
```
